[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "salesforce_erp_sync"
version = "0.1.0"
dependencies = ["prefect>=2.0"]

[tool.setuptools.packages.find]
where = ["src"]
